MAIN
DEFINE hhmm DATETIME HOUR TO MINUTE
DEFINE hhmmss DATETIME HOUR TO SECOND

    OPTIONS INPUT WRAP
    LET hhmmss = hhmm
    OPEN WINDOW w WITH FORM "timeedit"
    INPUT BY NAME hhmm,hhmmss ATTRIBUTES(UNBUFFERED, WITHOUT DEFAULTS=TRUE)
END MAIN
